//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3620
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weather.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap cloud_icon_5 {
            get {
                object obj = ResourceManager.GetObject("cloud_icon_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-8&quot;?&gt;
        ///&lt;IsraelCitiesWeatherForecastMorning&gt;&lt;Originator&gt;&lt;Organization&gt;Israel Meteorological Service&lt;/Organization&gt;&lt;Generator&gt;Global Distribution of Meteorological Information&lt;/Generator&gt;&lt;/Originator&gt;&lt;Identification&gt;&lt;Title&gt;Weather Forecast for Israel Cities (Morning)&lt;/Title&gt;&lt;IssueDateTime&gt;2012-01-28 00:58&lt;/IssueDateTime&gt;&lt;/Identification&gt;&lt;Location&gt;&lt;LocationMetaData&gt;&lt;LocationId&gt;520&lt;/LocationId&gt;&lt;LocationNameEng&gt;Elat&lt;/LocationNameEng&gt;&lt;LocationNameHeb&gt;אילת&lt;/LocationNameHeb&gt;&lt;Di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Weather {
            get {
                return ResourceManager.GetString("Weather", resourceCulture);
            }
        }
    }
}
